### ISSUE TITLE
sayAlert executed on every call

### ISSUE THREAD

**Issue by Mason10198** [Mason10198/SkywarnPlus#23]
Is there a provision for the alert to be shown on Supermon2 page like the original Autosky version would do? I have disable the original Autosky and have lost this. In order to have that, I have to have both enabled and have dual alerts.

_Originally posted by @aa5pd in https://github.com/Mason10198/SkywarnPlus/discussions/11#discussioncomment-6223371_

**Comment by Mason10198** [comment]
Implemented in `v0.2.3`

**Comment by aa5pd** [comment]
Outstanding, thank you very much

**Comment by aa5pd** [comment]
I have installed Version 2.3.  I am not getting any alerts. I have checked and rechecked my information and county code for my area and it is correct. My crontab is set currently for 1 min to update. I have just let the node it sit idle now for about 5 min and I have not gotten any all clear or even a script on the supermon2 page of no alerts.
Any Ideas?

**Comment by aa5pd** [comment]
I changed my county code over to a county in Georgia that is having Thunderstorms this evening. My alert went off and its showing on the Supermon2 page, However the crontab is set for every 1 min. 
At the end of 1 min the alert goes off again.
How can we fix this?

**Comment by Mason10198** [comment]
James, can you please upload the contents of your config.ini file, and your /tmp/SkywarnPlus/SkywarnPlus.log file?

**Comment by aa5pd** [comment]
Yes, I will do that. Just for a recap, I do have it working, but it continues to announce the alert after whatever time duration, you have set in the cronetab setting I will get those to you tomorrow

**Comment by Mason10198** [comment]
I made a typo, the config file is now config.yaml, not config.ini.

You mentioned that when you first set it up, you did not hear anything broadcasted. This is by design, as there were no alerts for your area. You did not hear the "all clear" message, because that message is played when the alerts go from an "active" state to a "cleared" state.

If you want to test the functionality of SkywarnPlus when setting it up, you can use the alert injection feature in the DEV section at the bottom of config.yaml to manually inject alerts.

As far as alerts being broadcasted every time the script runs, I suspect that SkywarnPlus is not able to access the data.json file in the TMP directory. This could be a permissions issue, a config.yaml issue, or something else.

Please upload the data.json along with the config and log files, if you are able. I'll see if I can help!

**Comment by aa5pd** [comment]
Sure will.

**Comment by Mason10198** [comment]
Oh, and you might also want to temporarily enable the `Debug: true` option in the `Logging` section of your config.yaml for a deeper look.

**Comment by aa5pd** [comment]
Mason, Here is the config.yaml file
:) Thanks

**Comment by Mason10198** [comment]
James, I'm not seeing the files. I think you'll have to upload them through Github instead of by email, by clicking the link at the bottom of this message.

**Comment by aa5pd** [comment]
It will not let me attach the file, we will do it like this :)


```# SkywarnPlus v0.2.3 Configuration File
# Author: Mason Nelson (N5LSN/WRKF394)
# Please edit this file according to your specific requirements.
#
# This config file is structured YAML.  Please be sure to maintain the structure when editing.
# YAML is very picky about indentation.  Use spaces, not tabs.

################################################################################################################################

SKYWARNPLUS:
  # Toggle the entire SkywarnPlus operation.
  # Set to 'True' to activate or 'False' to disable.
  # Example: Enable: true
  Enable: true

################################################################################################################################

Asterisk:
  # List of node numbers for broadcasting alerts. Multiple nodes are specified as a list.
  # Example:
  # Nodes:
  #   - 1998
  #   - 1999
  Nodes:
  - 57841

################################################################################################################################

Alerting:
  # Specify the county codes for which you want to pull weather data.
  # Find your county codes at https://alerts.weather.gov/.
  # Make sure to use county codes ONLY, NOT zone codes, otherwise you might miss out on alerts.
  # Example:
  # CountyCodes:
  #   - ARC121
  #   - ARC021
  CountyCodes:
  - OKC125
  # Enable instant voice announcement when new weather alerts are issued.
  # Set to 'True' for enabling or 'False' for disabling.
  # Example: SayAlert: true
  SayAlert: true
  # Enable instant voice announcement when weather alerts are cleared.
  # Set to 'True' for enabling or 'False' for disabling.
  # Example: SayAllClear: true
  SayAllClear: true
  # Limit the maximum number of alerts to process in case of multiple alerts.
  # SkywarnPlus fetches all alerts, orders them by severity, and processes only the 'n' most severe alerts, where 'n' is the MaxAlerts value.
  # MaxAlerts:
  # Specify an alternative path to the directory where sound files are located.
  # Default is SkywarnPlus/SOUNDS.
  # SoundsPath:

################################################################################################################################

Blocking:
  # List of globally blocked events. These alerts are ignored across the entire SkywarnPlus operation.
  # Use a case-sensitive list. Wildcards can be used.
  # Example:
  # GlobalBlockedEvents:
  #   - Flood Watch
  #   - '*Statement'
  #   - '*Advisory'
  GlobalBlockedEvents:
  # List of events blocked from being announced when received. These alerts will still be added to the tail message.
  # Use a case-sensitive list.
  SayAlertBlockedEvents:
  # List of events blocked from being added to the tail message. These alerts will still be announced when received.
  # Use a case-sensitive list.
  TailmessageBlockedEvents:

################################################################################################################################

Tailmessage:
  # Configuration for the tail message functionality. Requires initial setup in RPT.CONF.
  # Set 'Enable' to 'True' for enabling or 'False' for disabling.
  Enable: false
  # Specify an alternative path and filename for saving the tail message.
  # Default is /tmp/SkywarnPlus/wx-tail.wav.
  # TailmessagePath:

################################################################################################################################

CourtesyTones:
  # Configuration for the Courtesy Tones. Requires initial setup in RPT.CONF.
  # Set 'Enable' to 'True' for enabling or 'False' for disabling.
  Enable: false
  # Specify an alternative directory where tone files are located.
  # Default is SkywarnPlus/SOUNDS/TONES.
  # ToneDir:
  # Define the sound files for various types of courtesy tones.
  Tones:
    # Audio file to feed Asterisk as ct1 in "normal" mode
    CT1: Boop.ulaw
    # Audio file to feed Asterisk as ct2 in "normal" mode
    CT2: Beep.ulaw
    # Audio file to feed Asterisk as ct1 AND ct2 in "wx" mode
    WXCT: Stardust.ulaw
    # The file rpt.conf is looking for as ct1
    RptCT1: CT1.ulaw
    # The file rpt.conf is looking for as ct2
    RptCT2: CT2.ulaw
  # Define the alerts that trigger the weather courtesy tone.
  # Use a case-sensitive list. One alert per line.
  CTAlerts:
  - Ashfall Warning
  - Avalanche Warning
  - Blizzard Warning
  - Blowing Dust Warning
  - Civil Danger Warning
  - Civil Emergency Message
  - Coastal Flood Warning
  - Dust Storm Warning
  - Earthquake Warning
  - Evacuation - Immediate
  - Extreme Wind Warning
  - Fire Warning
  - Hazardous Materials Warning
  - Hurricane Force Wind Warning
  - Hurricane Warning
  - Ice Storm Warning
  - Law Enforcement Warning
  - Local Area Emergency
  - Nuclear Power Plant Warning
  - Radiological Hazard Warning
  - Severe Thunderstorm Warning
  - Shelter In Place Warning
  - Storm Surge Warning
  - Tornado Warning
  - Tornado Watch
  - Tropical Storm Warning
  - Tsunami Warning
  - Typhoon Warning
  - Volcano Warning
  - Winter Storm Warning

################################################################################################################################

IDChange:
  # Configuration for Automatic ID Changing. Requires initial setup in RPT.CONF and manual creation of audio files.
  Enable: false
  # Specify an alternative directory where ID files are located.
  # Default is SkywarnPlus/SOUNDS/ID.
  # IDDir:
  # Define the sound files for normal ID and weather ID.
  IDs:
    # Audio file to feed Asterisk as ID in "normal" mode
    NormalID: NORMALID.ulaw
    # Audio file to feed Asterisk as ID in "wx" mode
    WXID: WXID.ulaw
    # Audio file rpt.conf is looking for as ID
    RptID: RPTID.ulaw
  # Define the alerts that trigger the weather ID.
  # Use a case-sensitive list. One alert per line.
  IDAlerts:
  - Ashfall Warning
  - Avalanche Warning
  - Blizzard Warning
  - Blowing Dust Warning
  - Civil Danger Warning
  - Civil Emergency Message
  - Coastal Flood Warning
  - Dust Storm Warning
  - Earthquake Warning
  - Evacuation - Immediate
  - Extreme Wind Warning
  - Fire Warning
  - Hazardous Materials Warning
  - Hurricane Force Wind Warning
  - Hurricane Warning
  - Ice Storm Warning
  - Law Enforcement Warning
  - Local Area Emergency
  - Nuclear Power Plant Warning
  - Radiological Hazard Warning
  - Severe Thunderstorm Warning
  - Shelter In Place Warning
  - Storm Surge Warning
  - Tornado Warning
  - Tornado Watch
  - Tropical Storm Warning
  - Tsunami Warning
  - Typhoon Warning
  - Volcano Warning
  - Winter Storm Warning

################################################################################################################################

SkyDescribe:
  # SkyDescribe is a feature that allows you to request a detailed description of a weather alert.
  # VoiceRSS is a free service that SkyDescribe requires to function. You must obtain an API key from VoiceRSS.org.
  # See VoiceRSS.ors/api/ for more information
  # API Key for VoiceRSS.org
  APIKey:
  # VoiceRSS language code
  Language: en-us
  # VoiceRSS speech rate. -10 is slowest, 10 is fastest.
  Speed: 0
  # VoiceRSS voice profile. See VoiceRSS.org/api/ for more information.
  Voice: John
  # Maximum number of words to be spoken by SkyDescribe.
  # CAUTION: Setting this value too high may cause SkyDescribe to exceed the timeout timer of your node.
  # ~130 words is around 60 seconds at Speed: 0.
  MaxWords: 150

################################################################################################################################

AlertScript:
  # Completely enable/disable AlertScript
  Enable: false
  Mappings:
    # Define the mapping of alerts to either DTMF commands or bash scripts here.
    # Examples:
    #
    # This entry will execute the bash command 'asterisk -rx "rpt fun 1999 *123*456*789"'
    # when the alerts "Tornado Warning" AND "Tornado Watch" are detected.
    #
    # - Type: DTMF
    #   Nodes:
    #     - 1999
    #   Commands:
    #     - "*123*456*789"
    #   Triggers:
    #     - Tornado Warning
    #     - Tornado Watch
    #   Match: ALL
    #
    # This entry will execute the bash command '/home/repeater/testscript.sh'
    # and the bash command '/home/repeater/saytime.sh' when an alert whose
    # title ends with "Statement" is detected.
    #
    # - Type: BASH
    #   Commands:
    #     - "/home/repeater/testscript.sh"
    #     - "/home/repeater/saytime.sh"
    #   Triggers:
    #     - "*Statement"
    #
    # This entry will execute the bash command 'asterisk -rx "rpt fun 1998 *123*456*789"'
    # and the bash command 'asterisk -rx "rpt fun 1999 *123*456*789"' when an alert
    # titled "Tornado Warning" OR "Tornado Watch" is detected.
    #
    # - Type: DTMF
    #   Nodes:
    #     - 1998
    #     - 1999
    #   Commands:
    #     - "*123*456*789"
    #   Triggers:
    #     - Tornado Warning
    #     - Tornado Watch
    #
    # This entry will execute the bash command 'asterisk -rx "rpt fun 1999 *123*456*789"'
    # and the bash command 'asterisk -rx "rpt fun 1999 *987*654*321"'
    # when an alert titled "Tornado Warning" OR "Tornado Watch" is detected.
    #
    # - Type: DTMF
    #   Nodes:
    #     - 1999
    #   Commands:
    #     - "*123*456*789"
    #     - "*987*654*321"
    #   Triggers:
    #     - Tornado Warning
    #     - Tornado Watch
    #   Match: ANY
    #
    #
    # This is an example entry that will automatically execute SkyDescribe and
    # announce the full details of a Tornado Warning when it is detected.
  - Type: BASH
    Commands:
    - /usr/local/bin/SkywarnPlus/SkyDescribe.py "Tornado Warning"
    Triggers:
    - Tornado Warning

################################################################################################################################

Pushover:
  # Configuration for Pushover integration. Pushover is a free notification service. Register at https://pushover.net/.
  Enable: false
  # Provide your user key obtained from Pushover.
  UserKey:
  # Provide the API token obtained from Pushover.
  APIToken:
  # Enable verbose messaging
  Debug: false

################################################################################################################################

Logging:
  # Enable verbose logging
  Debug: true
  # Specify an alternative log file path.
  # LogPath:

################################################################################################################################

DEV:
  # Delete cached data on startup
  CLEANSLATE: true
  # Specify the TMP directory.
  TmpDir: /tmp/SkywarnPlus
  # Write alert titles to /tmp/AUTOSKY/alerts.txt for Supermon backwards compatibility.
  SupermonCompat: true
  # Enable test alert injection instead of calling the NWS API by setting 'INJECT' to 'True'.
  INJECT: false
  # List the test alerts to inject. Use a case-sensitive list. One alert per line.
  INJECTALERTS:
  - Tornado Warning
  - Tornado Watch
  - Severe Thunderstorm Warning
```

**Comment by Mason10198** [comment]
James, you have `Cleanslate` enabled in your config file. This option is for development and testing, and it forces SkywarnPlus to delete it's stored data every time it runs. This is why you are hearing alerts every minute.

**Comment by aa5pd** [comment]
My apologies I thought I had turned it off. I did that to clear it. Let me go back in and turn it back off. Also, are there any additional updates that I need to be aware of that are upcoming?

**Comment by Mason10198** [comment]
I did release a `v0.2.4` last night shortly after you installed `v0.2.3`. The update has a small bug fix, all you need to do is replace your `SkywarnPlus.py` with the `0.2.4` version.

I cannot say exactly if updates are "planned". I just come up with new ideas (or have them requested) or find bugs to fix and work on this project in my spare time.

**Comment by aa5pd** [comment]
LOL…. Well I just install this on another node.

We currently have weather statements in our area OKC125.

The fresh install is not giving any alerts.

Does the installation procedure include the new updated version v.0.2.4 or do I need to manually install that?

I followed the Installation instructions.




And of course as I'm typing this they clear all the alerts for my area. 










James Strauss
AA5PD
Cell:                       	918-636-5267
Radio Room:        	918-248-8554
Home HHUS		4533
Office HHUS		5759
Hams Over IP		100386
Allstar Node		57841
TGIF Bridge		TG 3140034
ZELLO			aa5pd
GMRS			WRPY436	
***@***.***


Confidentiality Notice:  This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information.  Any unauthorized review, use, disclosure or distribution is prohibited.  If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by aa5pd** [comment]
During the last alert, I got no alerts on the fresh install on the repeater node.

**Comment by Mason10198** [comment]
If you follow the install instructions, the latest version is installed automatically using `/latest` in the `wget` URL.

SkywarnPlus uses specific time data from the alerts assigned by the NWS to make sure an alert is "active" before processing it. These are called the `onset` and `ends` times.

Here is the documentation from the NWS API:
- `onset`: The expected time of the beginning of the subject event of the alert message.
- `ends`: The expected end time of the subject event of the alert message.
- `effective`: The effective time of the information of the alert message.
- `expires`: The expiry time of the information of the alert message.

From your description, I would assume that you determined an alert was active in your area from a source that uses the `expires` time, which in this case happened to last just a bit longer than the `ends` time for that alert which is used by SWP.

**Comment by aa5pd** [comment]
I have 2 allstar nodes here.. I did the original install on my personal node AA5PD. 

The second node Is the local repeater node, KG5BGO. My personal node would give the alerts but the BGO node was silent.

This was after following the install instructions. 

I will give it sometime and see if it fires any more alerts on my personal and watch the BGO at the same time.
My personal node appears to be working. 

:)

**Comment by aa5pd** [comment]
AA5PD Supermon2 Page

http://207.66.90.31:888/supermon2/link.php?nodes=57841,1997 <http://207.66.90.31:888/supermon2/link.php?nodes=57841,1997>

You can see the “No Alerts" tag




KG5BGO Supermon2 Page

http://207.66.90.31:888/supermon2/link.php?nodes=57841,1997 <http://207.66.90.31:888/supermon2/link.php?nodes=57841,1997>

This is the KG5BGO Supermon2 page.  You can see there is no tag. This is the install I did about an hour ago and it has done no alerts
We have had storms here all morning and my AA5PD node has been going off.

**Comment by Mason10198** [comment]
In `v0.2.3`, I was using `effective` and `expires` times to determine if the alert was active. In `v0.2.4` I changed this to `onset` and `ends` times instead.

`effective` and `expires` times relate to the information message itself, while `onset` and `ends` times relate to the actual alert itself contained within the information message, which is better for the use case of SWP.

If you have `v0.2.3` on one node, and `v0.2.4` on the other, this would explain the discrepancy in alerts.

I see that your Supermon looks quite different than "stock" Supermon, and it appears you might be using a different method of displaying alert data on the Supermon page. Can you share the Supermon code that displays those alerts? Can you confirm that it is getting the alerts from the `/tmp/AUTOSKY/alerts.txt` file? I implemented your requested feature of displaying alerts on Supermon, based on "stock" Supermon that comes included in the latest versions of HAMVOIP and ASL. That version of Supermon simply displays the plaintext contents of the file `/tmp/AUTOSKY/alerts.txt`. If yours is different, the feature might not be working for you.

**Comment by aa5pd** [comment]
Both of these system are running the same software with the exception that I did the fresh install with the updates on the KG5BGO system this morning.

If I go to the SkywarnPlus.py both are saying at the top that I am running V0.2.3. I see nothing saying v0.2.4

**Comment by aa5pd** [comment]
I am using supermon2

**Comment by Mason10198** [comment]
You are right, I forgot to update the version numbers at the top of the code when I uploaded `v0.2.4`. I just fixed this in the source code and re-uploaded the `v0.2.4` release ZIP.

It sounds like you have `v0.2.3` on the "personal" node, and `v0.2.4` on the KG5BGO node, which likely explains why you only heard an alert on the personal node, as it was using different time data to see if the alert was active.

Could you inject some test alerts using the section at the bottom of the `config.yaml` and see if they show up in Supermon? You can simply inject the alert titled "Test" if you do not want to inject a "real" alert for testing. That would look like this:

```
DEV:
  # Delete cached data on startup
  CLEANSLATE: false
  # Specify the TMP directory.
  TmpDir: /tmp/SkywarnPlus
  # Write alert titles to /tmp/AUTOSKY/alerts.txt for Supermon backwards compatibility.
  SupermonCompat: true
  # Enable test alert injection instead of calling the NWS API by setting 'INJECT' to 'True'.
  INJECT: false
  # List the test alerts to inject. Use a case-sensitive list. One alert per line.
  INJECTALERTS:
    - Test
```

**Comment by aa5pd** [comment]
Yes, question,  to update this I only need to re-install Skywarn plus correct?

Going to do my AA5PD one and just want to make sure. :)


I make a bunch of notes on this stuff and help other hams with it on a regular basis so I want to understand the fundamentals of it… LOL

**Comment by Mason10198** [comment]
Yes. In reality, you should only need to replace the `SkywarnPlus.py` file with the latest version, but I would recommend completely removing the SWP and TMP directories and doing a fresh install to make sure it's clean.
`rm -rf /usr/local/bin/SkywarnPlus/`
`rm -rf /tmp/SkywarnPlus/`

Let me know if the Supermon integration is working when you inject the test alert(s), or if you notice anything else.

**Comment by aa5pd** [comment]
Just for confirmation


Like this?


# Enable test alert injection instead of calling the NWS API by setting 'INJECT' to 'True'.
  INJECT: true

If this is correct, should the injection just show up on the supermon page?

**Comment by Mason10198** [comment]
Yes, and then at the very bottom of the config file, there is a list of alerts to inject. It will look like this:

```
DEV:
  # Delete cached data on startup
  CLEANSLATE: false
  # Specify the TMP directory.
  TmpDir: /tmp/SkywarnPlus
  # Write alert titles to /tmp/AUTOSKY/alerts.txt for Supermon backwards compatibility.
  SupermonCompat: true
  # Enable test alert injection instead of calling the NWS API by setting 'INJECT' to 'True'.
  INJECT: false
  # List the test alerts to inject. Use a case-sensitive list. One alert per line.
  INJECTALERTS:
    - Test
 ```

You should hear it broadcast the test alerts, and then you'll check to see if they show up in Supermon. If they do not, please check to see if the `/tmp/AUTOSKY/alerts.txt` file exists. If it does exist, please paste the contents of that file here.

**Comment by aa5pd** [comment]
In /tmp/AUTOSKY/.  I have no file called alerts.txt

**Comment by Mason10198** [comment]
Did SkywarnPlus execute and announce the test alerts? Is the `SupermonCompat` option enabled at the bottom of the config file, right above the `INJECT` setting?

**Comment by aa5pd** [comment]
Yes, it is set to true and no they did not announce.

**Comment by Mason10198** [comment]
Please follow these steps:
1. Disable the `crontab` entry by commenting out the line `#* * * * * /usr/local/bin/SkywarnPlus/SkywarnPlus.py`
2. Set `Debug: true` in the `Logging` section of the SkywarnPlus `config.yaml` file
3. Remove the tmp directory: `rm -rf /tmp/SkywarnPlus/`
4. Manually execute SkywarnPlus: `/usr/local/bin/SkywarnPlus/SkywarnPlus.py`
5. Upload the contents of the `/tmp/SkywarnPlus/SkywarnPlus.log` file here.

**Comment by aa5pd** [comment]
Am I missing something?

I can not Manually execute SkywarnPlus.

Can you provide me the exact line to type in so it would execute?

**Comment by Mason10198** [comment]
The exact command to execute it manually is:

`/usr/local/bin/SkywarnPlus/SkywarnPlus.py`

**Comment by aa5pd** [comment]
LOL. Thats what I had.. This is what I got..

**Comment by Mason10198** [comment]
If you pasted the contents of your log file, they did not come through

**Comment by aa5pd** [comment]
This is what I get when I try to manually execute it




***@***.*** SkywarnPlus]# /usr/local/bin/SkywarnPlus/SkywarnPlus.py
bash: /usr/local/bin/SkywarnPlus/SkywarnPlus.py: /usr/bin/python3^M: bad interpreter: No such file or directory
***@***.*** SkywarnPlus]#

**Comment by Mason10198** [comment]
Ugh, I do apologize. That is a repeat issue caused by my code editor. I thought I had it permanently fixed. I just reuploaded the `v0.2.4` ZIP yet again, and it should be fixed. You can keep using the same `config.yaml` file after downloading the files again if you want, no need to delete it and reconfigure it.

**Comment by aa5pd** [comment]
Hey, Its not a problem.. I appreciate your working on this.. and I get to learn :) 

Just for confirmation, what do I need to do?  Re-install Skywarn Plus?

**Comment by Mason10198** [comment]
Yes, please re-install (do not add the crontab entry yet) and then:

Set "Debug: true" in the "Logging" section of the SkywarnPlus "config.yaml" file

Enable test alert injection in "config.yaml"

Manually execute SkywarnPlus

Paste the contents of the "/tmp/SkywarnPlus/SkywarnPlus.log" file here.

Check to see if the "/tmp/AUTOSKY/alerts.txt" file exists and paste the contents here

**Comment by aa5pd** [comment]
Here we go 😊James StraussAA5PDOn Jun 21, 2023, at 3:57 PM, Mason10198 ***@***.***> wrote:﻿
Yes, please re-install (do not add the crontab entry yet) and then:
Set "Debug: true" in the "Logging" section of the SkywarnPlus "config.yaml" file
Enable test alert injection in "config.yaml"
Manually execute SkywarnPlus
Paste the contents of the "/tmp/SkywarnPlus/SkywarnPlus.log" file here.
Check to see if the "/tmp/AUTOSKY/alerts.txt" file exists and paste the contents here

**Comment by aa5pd** [comment]
I have reinstalled, but when I try to manually executed, I still get the same errorJames StraussAA5PDOn Jun 21, 2023, at 3:59 PM, james Strauss ***@***.***> wrote:﻿Here we go 😊James StraussAA5PDOn Jun 21, 2023, at 3:57 PM, Mason10198 ***@***.***> wrote:﻿
Yes, please re-install (do not add the crontab entry yet) and then:
Set "Debug: true" in the "Logging" section of the SkywarnPlus "config.yaml" file
Enable test alert injection in "config.yaml"
Manually execute SkywarnPlus
Paste the contents of the "/tmp/SkywarnPlus/SkywarnPlus.log" file here.
Check to see if the "/tmp/AUTOSKY/alerts.txt" file exists and paste the contents here

**Comment by aa5pd** [comment]
Incorrect number of arguments. Please provide the key and the new value.
Usage: python3 /usr/local/bin/SkywarnPlus/SkyControl.py <key> <value>

**Comment by aa5pd** [comment]
I still get the error when manual execute. 

I dont have a /tmp/SkywarnPlus/Skywarnplus.log file.  ( is this because I cant manually fire it?)

I do not have a /tmp/AUTOSKY/alerts.txt file

**Comment by Mason10198** [comment]
Me and James hopped on a meeting together and ran this thing down... the issue was me improperly exporting the release ZIPs at just the right time to confuse us.

It is worth noting that the Supermon compatibility feature in SWP works great with Supermon 6.1 that ships with ASL/HAMVOIP, but newer versions of Supermon appear to get alert data from an external internet source by default and do not even need be provided alerts from SWP.

`v0.2.5` resolves all issues mentioned in this thread.
